# Práctica Clase 3

## Numpy

In [6]:
pip install numpy

     --------------------------------------- 14.7/14.7 MB 21.8 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
You should consider upgrading via the 'C:\Users\Hiros\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip' command.


In [1]:
import numpy as np

**Ejercicio 1**: Responder las siguientes preguntas:
* ¿Qué operaciones se pueden hacer tanto en un arreglo de Numpy como en una lista? Dar un ejemplo en una celda.
* ¿Qué operaciones se pueden hacer en un arreglo de Numpy pero NO en una lista? Explorar algunas opciones y dar un ejemplo en una celda.
* ¿Cuál es la diferencia entre un arreglo de forma -shape- (n,), (n,1) y (1,n)? Pueden crear arreglos para intentar responder esa pregunta.

A partir de una lista podemos crear un arreglo de numpy

In [11]:
print("En una lista no se puede hacer slicing fácilmente\n",
    "no se pueden crear arrays de varias dimensiones o en general\n",
    "los arrays te abren las posibilidades de hacer operaciones \n",
    "en varias dimensiones cuando las listas sólo te permiten uno.")


En una lista no se puede hacer slicing fácilmente
 no se pueden crear arrays de varias dimensiones o en general
 los arrays te abren las posibilidades de hacer operaciones 
 en varias dimensiones cuando las listas sólo te permiten uno.


In [9]:
print("Creo que una lista está muy limitado por la misma naturaleza del Python, en cambio un array ya viene preparado para aplicarle todas las funcionalidades del Numpy\n",
        "por ejemplo me parece que en una lista puedo sacar un promedio usando for y dividiendolo por el len de la lista, pero con un array sería una simple línea de código.")
lista = [0,1,2,3,4,5]
arreglo = np.array(lista)

# para sacar el promedio usando lista:
sumalista=0
for i in lista:
    sumalista+=i
print("el promedio sacado con la lista es: ",(sumalista/len(lista)))

# para sacar promedio usando array:
print("el promedio sacado con un array es: ",np.mean(arreglo))


Creo que una lista está muy limitado por la misma naturaleza del Python, en cambio un array ya viene preparado para aplicarle todas las funcionalidades del Numpy
 por ejemplo me parece que en una lista puedo sacar un promedio usando for y dividiendolo por el len de la lista, pero con un array sería una simple línea de código.
el promedio sacado con la lista es:  2.5
el promedio sacado con un array es:  2.5


In [30]:
lista = [0,1,2,3,4,5]
arreglo = np.array(lista)
print(lista)
print(arreglo)

[0, 1, 2, 3, 4, 5]
[0 1 2 3 4 5]


Pero para algunos casos numpy tiene funciones que crean listas más rápidamente.

In [12]:
arreglo = np.arange(8)
print(arreglo)

[0 1 2 3 4 5 6 7]


Algunas cosas que se pueden hacer con arreglos pero no con las listas:

1. Sumarle un mismo elemento

In [13]:
lista + 1

TypeError: can only concatenate list (not "int") to list

In [20]:
arreglo = arreglo + 1

In [35]:
arreglo

array([[1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6]])

2. Elevar al cuadrado todos los elementos

In [22]:
lista**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [25]:
arreglo**2

array([ 16,  25,  36,  49,  64,  81, 100, 121])

3. Sumar todos los elementos

In [31]:
print(arreglo.sum())
print(lista.sum())

15


AttributeError: 'list' object has no attribute 'sum'

In [32]:
n = 0
for e in lista:
    n = n + e
print(n)

15


In [37]:
arreglo.shape

(3, 6)

In [38]:
arreglo = np.array([[1,2,3,4,5,6],[1,2,3,4,5,6],[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]] . Shape = (3, 6) 



In [39]:
arreglo = np.array([[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")

[[1 2 3 4 5 6]] . Shape = (1, 6) 



In [40]:
arreglo = np.array([[1,2,3,4,5,6]]).T #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] . Shape = (6, 1) 



In [41]:
#¿Cuál es la diferencia entre un arreglo de forma -shape- (n,), (n,1) y (1,n)?

print('Arreglo de (n,)')
arreglo = np.array([1,2,3,4,5,6])
print(arreglo,'. Shape =', arreglo.shape, "\n") # "\n" imprime un salto de linea

print('Arreglo de (2,n)')
arreglo = np.array([[1,2,3,4,5,6],[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")

print('Arreglo de (n,1)')
arreglo = np.array([[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo.T,'. Shape =', arreglo.T.shape, "\n")   #notar .T, que significa transpuesto


Arreglo de (n,)
[1 2 3 4 5 6] . Shape = (6,) 

Arreglo de (2,n)
[[1 2 3 4 5 6]
 [1 2 3 4 5 6]] . Shape = (2, 6) 

Arreglo de (n,1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] . Shape = (6, 1) 



In [42]:
### EXTRA 1###
#Trasponer no es la unica forma de crear un arreglo de forma (n,1)'''
arreglo = np.array([[1],[2],[3],[4],[5],[6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape)   #notar .T, que significa transpuesto

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] . Shape = (6, 1)


In [43]:
a1 = np.array([[1,2,3,4],[5,6,7,8]])
a1.shape

(2, 4)

In [44]:
a2 = np.array([[1,2,3,4],[5,6,7,8]])
a2.shape

(2, 4)

In [45]:
a3 = a1 * a2
a3.shape

(2, 4)

In [46]:
a3

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

**Ejercicio 2**:
* Escribir un arreglo con números enteros del 0 al 9. Pista: arange
* Escribir un arreglo con 100 números equiespaciados del 0 al 9. Pista: linspace

In [51]:
hio=np.arange(10)
print(hio)
hio2=np.linspace(0,9,100)
print(hio2)

[0 1 2 3 4 5 6 7 8 9]
[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091 1.
 1.09090909 1.18181818 1.27272727 1.36363636 1.45454545 1.54545455
 1.63636364 1.72727273 1.81818182 1.90909091 2.         2.09090909
 2.18181818 2.27272727 2.36363636 2.45454545 2.54545455 2.63636364
 2.72727273 2.81818182 2.90909091 3.         3.09090909 3.18181818
 3.27272727 3.36363636 3.45454545 3.54545455 3.63636364 3.72727273
 3.81818182 3.90909091 4.         4.09090909 4.18181818 4.27272727
 4.36363636 4.45454545 4.54545455 4.63636364 4.72727273 4.81818182
 4.90909091 5.         5.09090909 5.18181818 5.27272727 5.36363636
 5.45454545 5.54545455 5.63636364 5.72727273 5.81818182 5.90909091
 6.         6.09090909 6.18181818 6.27272727 6.36363636 6.45454545
 6.54545455 6.63636364 6.72727273 6.81818182 6.90909091 7.
 7.09090909 7.18181818 7.27272727 7.36363636 7.45454545 7.54545455
 7.63636364 7.72727273 7.81818182 7.90909091 8.         

**Ejercicio 3**:
* Escribir un arreglo con números enteros del 10 al 100 y seleccionar aquellos que son divisibles por 3<br>
Pista: mask

In [53]:
hio3=np.arange(10,100)
hio3[hio3%3==0]

array([12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60,
       63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

**Ejercicio 4**:
* Crear un arreglo de ceros de `shape` (5,10).
* Reemplazar la segunda y cuarta fila con unos
* Reemplazar la tercera y octava columna con dos (2).

In [65]:
hio4=np.full((5,10),0)
print(hio4,"\n")

hio4[(2,4),:]=1
print(hio4,"\n")

hio4[:,(3,8)]=2
print(hio4,"\n")

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]] 

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1]] 

[[0 0 0 2 0 0 0 0 2 0]
 [0 0 0 2 0 0 0 0 2 0]
 [1 1 1 2 1 1 1 1 2 1]
 [0 0 0 2 0 0 0 0 2 0]
 [1 1 1 2 1 1 1 1 2 1]] 



**Ejercicio $\infty$**:
Hacer todos los ejercicios que puedan del siguiente link https://www.machinelearningplus.com/python/101-numpy-exercises-python/

O de https://github.com/rougier/numpy-100

Para explorar las funciones de creación de datos aleatorios:
https://numpy.org/doc/stable/reference/random/legacy.html

In [66]:
a = np.random.random((4,2,3)) * 100 + 100
a

array([[[129.29479331, 126.7449565 , 105.69675198],
        [182.57772904, 195.75042168, 116.48916572]],

       [[141.95797877, 115.62098054, 153.66160933],
        [188.31394583, 159.44706016, 191.4628193 ]],

       [[155.85921704, 126.24931791, 104.96851346],
        [131.90943157, 170.6679412 , 111.14864642]],

       [[108.6744964 , 156.64534744, 108.21148722],
        [131.62907957, 197.35341786, 199.10376865]]])

In [67]:
a = np.random.random((4,4))

In [68]:
a

array([[0.3903421 , 0.75005649, 0.11131143, 0.03134943],
       [0.83839972, 0.30381654, 0.39153845, 0.15465581],
       [0.44983429, 0.5650365 , 0.04902008, 0.84109644],
       [0.94129878, 0.2806174 , 0.6373633 , 0.99470958]])

In [69]:
a = np.array([[10,200,30,45,5,50],[5,20,30,40,50,0],[5,20,30,40,50,0],[5,20,30,40,50,0]], dtype=np.int8)

In [70]:
a

array([[ 10, -56,  30,  45,   5,  50],
       [  5,  20,  30,  40,  50,   0],
       [  5,  20,  30,  40,  50,   0],
       [  5,  20,  30,  40,  50,   0]], dtype=int8)

In [71]:
a.sum()

519

In [72]:
a.std()

23.924904214367643

In [73]:
a.sort(axis=1)

In [74]:
a

array([[-56,   5,  10,  30,  45,  50],
       [  0,   5,  20,  30,  40,  50],
       [  0,   5,  20,  30,  40,  50],
       [  0,   5,  20,  30,  40,  50]], dtype=int8)

In [75]:
a.sort(axis=0)
a

array([[-56,   5,  10,  30,  40,  50],
       [  0,   5,  20,  30,  40,  50],
       [  0,   5,  20,  30,  40,  50],
       [  0,   5,  20,  30,  45,  50]], dtype=int8)

In [76]:
a[1:3,0:3]

array([[ 0,  5, 20],
       [ 0,  5, 20]], dtype=int8)

In [77]:
l =   [[ 10, 200,  30,  45,   5, 100],
       [  5,  20,  30,  40,  50,   0],
       [  5,  20,  30,  40,  50,   0],
       [  5,  20,  30,  40,  50,   0]]

In [78]:
a = np.array([l])

In [79]:
a.shape

(1, 4, 6)

In [81]:
a.reshape(24)

array([ 10, 200,  30,  45,   5, 100,   5,  20,  30,  40,  50,   0,   5,
        20,  30,  40,  50,   0,   5,  20,  30,  40,  50,   0])

In [82]:
a = np.matrix([[1,2,3,4,5,6]]) 
print(a) 

[[1 2 3 4 5 6]]


In [83]:
b = np.matrix([[1],[2],[3],[4],[5],[6]]) 
print(b) 

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [84]:
c = a * b 
print(c) 

[[91]]


In [85]:
d = b * a 
print(d)

[[ 1  2  3  4  5  6]
 [ 2  4  6  8 10 12]
 [ 3  6  9 12 15 18]
 [ 4  8 12 16 20 24]
 [ 5 10 15 20 25 30]
 [ 6 12 18 24 30 36]]
